#! /bin/sh 
set -eux

COSMO_LIBDIR=$(realpath "./libcosmo/")
HEADER_PATHS=$(realpath "./header_stubs")
CC="${CC:-gcc}"

if [ ! -f $COSMO_LIBDIR/cosmopolitan.h ]; then
    echo "<<<SUPERCONFIGURE>>> cosmopolitan.h does not exist in $COSMO_LIBDIR!!!!"
    exit 1
fi

echo "<<<SUPERCONFIGURE>>> cosmopolitan.h exists in $COSMO_LIBDIR, assuming other files exist as well"

echo "<<<SUPERCONFIGURE>>> Running configure with $CC"
LD_LIBRARY_PATH="" \
    OPT="" \
    CCSHARED="" \
    LINKFORSHARED="" \
    PKG_CONFIG="" \
    CFLAGS="-g3 -Wall -Wno-strict-prototypes -Wno-unused-value \
      -std=c99 -static \
      -fno-pie \
      -mno-red-zone \
      -nostdinc -nostdlib \
      -I$HEADER_PATHS \
      -include $COSMO_LIBDIR/cosmopolitan.h" \
    LDFLAGS="-static -nostdlib -nostdinc \
      -fno-pie -mno-red-zone \
      -include $COSMO_LIBDIR/cosmopolitan.h" \
    LIBS="\
      -Wl,--gc-sections -fuse-ld=bfd \
      -Wl,-T,$COSMO_LIBDIR/ape.lds \
      -include $COSMO_LIBDIR/cosmopolitan.h \
      $COSMO_LIBDIR/crt.o \
      $COSMO_LIBDIR/ape.o \
      $COSMO_LIBDIR/cosmopolitan.a" \
    CFLAGS_NODIST="-Wall -Wno-strict-prototypes -Wno-unused-value \
      -std=c99 -static \
      -fno-pie \
      -mno-red-zone \
      -nostdinc -nostdlib \
      -I$HEADER_PATHS \
      -include $COSMO_LIBDIR/cosmopolitan.h"\
    ./configure \
        --prefix="./libcosmo/" \
        --enable-blas   \
        --enable-cblas  \
        --enable-verbose-make \
        --enable-arg-max-hack \
        --enable-static \
        --disable-shared \
        --enable-threading=no \
        --disable-system \
        --disable-rpath \
        penryn

echo "<<<SUPERCONFIGURE>>> Running make"
make -j4

echo "<<<SUPERCONFIGURE>>> Running make install into $(COSMO_LIBDIR)"
make install

echo "<<<SUPERCONFIGURE>>> DONE. Go to examples/oapi/ and run the examples"
